{% set name = "apispec" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79029486d36a0d7f3c659dbf6ae50a91fbed0c22dcd5376f592e076c130bc7f9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pyyaml >=3.10

test:
  imports:
    - apispec

about:
  home: https://github.com/marshmallow-code/apispec
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pluggable API specification generator

  description: |
    A pluggable API specification generator. Currently supports the OpenAPI
    specification (f.k.a. Swagger 2.0).
  doc_url: http://apispec.readthedocs.io/
  dev_url: https://github.com/marshmallow-code/apispec

extra:
  recipe-maintainers:
    - frol
    - rth
    - carlodri
